#!/usr/bin/env bash
# Set up Nginx to include a custom header (X-Served-By) in its HTTP responses on web-01 and web-02.
# The X-Served-By header's value should be the hostname of the Nginx server.

sudo apt-get update
sudo apt-get -y install nginx

#Configure the firewall to allow port 80 HTTP requests
sudo ufw allow 'Nginx HTTP'

#Create necessary dir and set permissions for web content
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# Create default index page
echo 'Hello World' | sudo tee /var/www/html/index.html

# Configure redirect for page(/redirect_me) and custom header to display servername
header_cfg="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/lologic.tech permanent;"
sudo sed -i "s|server_name _;|$header_cfg|" /etc/nginx/sites-enabled/default

sudo service nginx restart

