#!/usr/bin/env bash
# Script to install and confiure HAproxy on server
# Distribute traffic via round robin algorithm

sudo apt-get update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend app-frontend
        bind *:80
        mode http
        default_backend app-backend
backend app-backend
        balance roundrobin
        server 331633-web-01 54.162.46.205:80 check
        server 331633-web-02 107.23.64.101:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable init script starting
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

