#!/usr/bin/env bash
# Q - find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
# solved by:
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
