#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Allow the system to search for Bash interpreter in user's PATH env variable

for((i = 1; i <= 10; i++))
do
	echo "Best School"
done
