#!/usr/bin/env bash
# Loop 1- 10 display bad luck for 4, good luck for 8 and rest Best School

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
